Feature: allow forked PRs to access repo secrets after approval
1Password/onepassword-sdk-python pull request #42
Opened 2024-05-23 14:51 UTC by AndyTitu

## Summary

This PR enables integration tests to be run on forked PRs, via the `ok-to-test` command.

Credits to https://github.com/imjohnbo/ok-to-test for the idea and the GitHub actions implementation!

## Thought process
The flow is also explained in this README as well: https://github.com/imjohnbo/ok-to-test

- `integration-test-trusted` is only run on internal PRs and is skipped on forked PRs
- `integration-test-fork` will always be skipped on internal PR and be marked as skipped on forked PRs before the `/ok-to-test sha=commit_sha_to_test` command is added by a collaborator with write permissions to the repo.
- once the `/ok-to-test` command is commented in the PR, the `integration-test-fork` will run on the sdk repo with secrets access and if it's successful it'll update the check pipeline of the forked PR.

## Additional Considerations
A new dependency was added, namely the `peter-evans/slash-command-dispatch@v3` (very popular repo with 550 stars) for using the `/ok-to-test` command which requires a `PERSONAL_ACCESS_TOKEN`. 
We'll be using the 1password-bot for the personal access token: @1PasswordPackagesBot

## How to Test
I tested this flow out in a personal repo. See this PR for how it looks like: https://github.com/AndyTitu/test-ok-to-test/pull/16

2024-05-28 12:29 UTC, AndyTitu commented on .github/workflows/validate.yml
> +  # It will checkout the forked (and now trusted) code and it will run the integration tests on it.
We might consider refactoring this GitHub action into its own repo and publishing to GitHub marketplace so we can make the solution re-usable across repos, after it's been approved.

2024-06-10 16:28 UTC, mathieulj requested changes

2024-06-10 16:28 UTC, mathieulj commented on .github/workflows/validate.yml
> +        ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
**issue** We should checkout the exact sha hash we validated against otherwise we are open to races (ex. if the contributor pushes a new commit just in time)

```suggestion
        ref: '${{ github.event.client_payload.pull_request.head.sha }}'
```

2024-06-10 16:28 UTC, mathieulj commented on .github/workflows/validate.yml
> +    - uses: actions/checkout@v4
**issue** If I'm not mistaken, this second checkout will wipe out the first so we wouldn't be running the pipeline on the exact commit/branch we've selected.

```suggestion
```

2024-06-11 12:11 UTC, AndyTitu commented on .github/workflows/validate.yml
> +    - uses: actions/checkout@v4
Done, thanks for catching this!

2024-06-11 12:11 UTC, AndyTitu commented on .github/workflows/validate.yml
> +        ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
Done, thanks for catching!

2024-06-11 14:24 UTC, mathieulj commented on .github/workflows/validate.yml
> +          const ref = pull.head.sha;
**suggestion:** Sorry I didn't spot this the first time around but we should probably be using `github.event.client_payload.pull_request.head.sha` as a ref here also rather than fetching the latest head.

2024-06-20 08:10 UTC, Marton6 commented on .github/workflows/validate.yml
> +  # It will checkout the forked (and now trusted) code and it will run the integration tests on it.
That's exactly what I was thinking. That would be great for increasing the impact of this work.

2024-06-20 10:10 UTC, Marton6 commented on .github/workflows/validate.yml
> +    - uses: actions/github-script@v6
What exactly does this step do?

2024-06-21 11:39 UTC, AndyTitu commented on .github/workflows/validate.yml
> +    - uses: actions/github-script@v6
This is the official "scripting" GitHub Action that allows us to script some custom logic that'll get execute in our workflows. 

This step specifically updates the workflow on the user's PR workflow summary with the status of the pipeline run on the head of our main branch as part of the repository_dispatch triggered workflow that checks out the user's code.

2024-06-21 11:43 UTC, AndyTitu commented on .github/workflows/validate.yml
> +  # It will checkout the forked (and now trusted) code and it will run the integration tests on it.
I propose we do this refactor in order to adopt this strategy on all repos after we tested this approach out on this SDK repo and we confirmed everything suits our needs.

2024-06-24 10:14 UTC, Marton6 commented on .github/workflows/validate.yml
> +    - uses: actions/github-script@v6
Thanks for clarifying!

2024-06-24 10:14 UTC, Marton6 commented on .github/workflows/validate.yml
> +  # It will checkout the forked (and now trusted) code and it will run the integration tests on it.
Sounds good to me!

2024-06-24 10:14 UTC, Marton6 approved these changes

2024-08-14 10:02 UTC, merged