Add init function for exposing items and secrets APIs
1Password/onepassword-sdk-python pull request #49
Opened 2024-06-03 09:03 UTC by AndyTitu

2024-06-04 14:00 UTC, Marton6 requested changes

2024-06-04 14:00 UTC, Marton6 commented on src/onepassword/__init__.py
>      "DEFAULT_INTEGRATION_NAME",
This file is automatically generated so let's not change it manually here, as these changes will be reverted when we release next.

We should update this in the code generator and, while we're at it, we should also add a message to the top of this file stating that it is an automatically generated file. This should prevent us from accidentally changing it without knowing that it's generated.

2024-06-04 14:13 UTC, AndyTitu commented on src/onepassword/client.py
> +        authenticated_client._config = config
We only keep track of it so we can test that the client was initialised with the correct config

2024-06-04 14:13 UTC, AndyTitu commented on src/onepassword/__init__.py
>      "DEFAULT_INTEGRATION_NAME",
I suppose we can still leave these here but also update the code generator as well. I see no reason to remove these now.

2024-06-04 14:29 UTC, Marton6 commented on src/onepassword/client.py
> +        authenticated_client._config = config
That sounds like an anti pattern. We shouldn't add fields like this one just for testing purposes, especially since we can achieve the same coverage by simply unit testing the `new_default_config` function

2024-06-05 08:08 UTC, AndyTitu commented on src/onepassword/client.py
> +        authenticated_client._config = config
Removed the config and tests that use it

2024-06-05 08:08 UTC, AndyTitu commented on src/onepassword/__init__.py
>      "DEFAULT_INTEGRATION_NAME",
Fixed

2024-06-05 08:23 UTC, Marton6 requested changes

2024-06-05 08:23 UTC, Marton6 commented on src/onepassword/client.py
It seems that this file is also auto-generated. So again, we should update the code generator first, add a comment to the top of the file signaling that it has been auto generated and then update this MR with the newly generated file.

2024-06-05 08:32 UTC, AndyTitu commented on src/onepassword/client.py
Done

2024-06-05 09:31 UTC, Marton6 commented on src/onepassword/client.py
> +		client_id = int(await _init_client(config))
We seem to be using both tabs and spaces here, let's stick to one of them as this could cause warnings and errors in python

2024-06-05 09:39 UTC, Marton6 commented on src/onepassword/test_client.py
Let's remove this comment if we've removed the test below it

2024-06-05 09:39 UTC, Marton6 approved these changes

2024-06-05 09:45 UTC, Marton6 commented
<img width="705" alt="Screenshot 2024-06-05 at 11 44 50" src="https://github.com/1Password/onepassword-sdk-python/assets/13394704/88ce9731-6849-41e8-9a1c-1a7fd28b76f2">

One possibly confusing thing is that now types like `Item` can be imported in 3 different ways, not sure how big of a problem that is.

2024-06-05 09:45 UTC, AndyTitu commented on src/onepassword/test_client.py
We're still testing the client constructor so the comment is still valid. We only removed one test case that tested the constructor, not all of them

2024-06-05 09:50 UTC, AndyTitu commented
@Marton6 for me that doesn't show up like that. For a customer that shouldn't show up either. The `from onepassword.items import Item` option doesn't make sense since we're not exposing anything from the items file/module except for the `Items` API.

Even your `from onepassword.client import Items` doesn't make sense

2024-06-05 09:55 UTC, Marton6 commented
> @Marton6 for me that doesn't show up like that. For a customer that shouldn't show up either. The `from onepassword.items import Item` option doesn't make sense since we're not exposing anything from the items file/module except for the `Items` API.

I tested it out and both work for me perfectly well. I also confirmed that I'm testing the latest commit on this branch.

2024-06-05 11:55 UTC, merged