Add python toolchain-script
1Password/onepassword-sdk-python pull request #52
Opened 2024-06-07 15:32 UTC by MOmarMiraj

This MR will create a two step release process that you can run on any branch and release the Python SDK.

This requires GitLab CLI installed and the MakeFile checks if you have it or not.

Also, a PAT will have to be created and exported to GITHUB_CLI_TOKEN environment variable to run the gitlab CLI. The minimum required scopes for the token are: repo, read:org, and gist.

The first script prep-release.sh will update the version/build numbers and create a new changelog for the release

The second script release.sh will create the release branch, add all necessary files, and create the release with the correct changelog and version

This process will ensure that the developer can verify the files before pushing a release.

A README is in the `src/onepassword/changelogs` folder on step by step process on how to push a release.

Was tested on fork of the repo.
Build Number:
![image](https://github.com/1Password/onepassword-sdk-python/assets/103403052/adf89b56-7d18-411f-a168-9a1c9908f583)
Version:
![image](https://github.com/1Password/onepassword-sdk-python/assets/103403052/9655080c-c5c0-47a7-ad32-eb0b173ccc68)

## To Test
1. Go into the test python sdk repo (https://github.com/MOmarMiraj/onepassword-sdk-python). I sent you three all invites to access the repo which should give you the correct permissions.
3. Test on main/feature branch.. run `make prep-release`.. follow instructions
4. Run `make release`

I have updated the fork repo to include the latest changes and edited it so the release will be created on the fork repo not the actual repo.. so just run the scripts and should be good to go.

2024-06-12 08:35 UTC, hculea commented on scripts/prep-release.sh
> +current_build_number=$(< src/onepassword/version-build)
no need for this, correct?

2024-06-12 08:37 UTC, hculea commented on scripts/prep-release.sh
> +
All the comments I've left on the Go SDK MR stand for these two scripts as well, here. I will only review the other files.

2024-06-12 08:37 UTC, hculea commented on src/onepassword/version
> +0.1.0-beta.10
Let's make sure these have a proper new line at their end.

2024-06-12 08:40 UTC, hculea commented on src/onepassword/version
> +0.1.0-beta.10
Also, I see no good reason for these to be within `src/onepassword`. I'd place them in the root of the repo, but leaving it to your discretion. The user shouldn't have to concern with this, though

2024-06-12 12:49 UTC, MOmarMiraj commented on scripts/prep-release.sh
> +current_build_number=$(< src/onepassword/version-build)
Similar to Go SDK, we just need the `current_build_number` as we compare it to the updated `build` to ensure that the build number is updated and we are not trying to release the same version

2024-06-12 12:58 UTC, MOmarMiraj commented on src/onepassword/version
> +0.1.0-beta.10
Moved them to the root of the repo and updated script accordingly.

2024-06-12 13:52 UTC, MOmarMiraj commented on scripts/prep-release.sh
> +
Updated to match Go SDK.

2024-06-14 08:05 UTC, hculea commented on templates/defaults.tpl.py
> +SDK_VERSION =  "{{ BUILD }}" # v{{ VERSION }}
My preference would be that we include as little as possible in this templates.

So what I would do here is:
* create a `version.py` template, that only contains templated global vars for version and build
* import the version & build from that file in the appropriate places, such as here.

90% of this file doesn't have to be templated, and this can easily become a source of bugs, once we begin changing the source code without minding the template. Ensuring that template is as small as possible minimizes the risk for such bugs.

2024-06-14 08:06 UTC, hculea requested changes
Only one comment above, otherwise I agree with the approach, as it is in line with what we do for Go SDK.

2024-06-14 15:03 UTC, MOmarMiraj commented on templates/defaults.tpl.py
> +SDK_VERSION =  "{{ BUILD }}" # v{{ VERSION }}
Great feedback, thanks and fixed!

2024-06-25 12:41 UTC, AndyTitu commented on src/release/changelogs/0.1.0-beta.11-0010011
What is the reason behind having this `changelogs` folder that keeps accruing changelog files in it? Internally we're using this folder so we can keep track of the features/fixes/improvements we introduce, but I don't expect a lot of these to happen on the open source repos. The bulk of user-facing changes will occur on the sdk-core repo so we can keep track of changelogs there. From what I see the file stored in here is only used so that we can pass the release notes written in the `prep-release` script to the `release` script.
Can we then just:
- delete the changelogs folder
- only have 1 file`./src/release/notes`
- modify the scripts such that the `prep-release` script saves the release notes in the release notes file, and then the `release` script reads from that file?

Then we will only have one file which holds the latest release notes in the repo (we keep it because it might be useful for folks that download a certain version to check the release notes to see what the code they're using does), and we won't store the full release notes history in the repo (because I don't see why people would like to see the full release note history in each version of the code they download + that it makes it difficult to now when it's time to delete notes, since we can't decide that we're just going to keep storing these in here forever until we have a 1000 files folder)

2024-06-25 12:44 UTC, AndyTitu commented on src/release/scripts/prep-release.sh
> +sed -e "s/{{ build }}/$build/" -e "s/{{ version }}/$version/" "$version_template_file" > "$output_version_file"
The above comment doesn't reflect what the actual behaviour of the script is

2024-06-25 12:44 UTC, AndyTitu commented on src/release/templates/version.tpl.py
> +SDK_BUILD_NUMBER = "{{ build }}"
I think it's be fine if we added a new line in here

2024-06-25 12:45 UTC, AndyTitu commented on src/release/version.py
> +SDK_BUILD_NUMBER = "0010011"
nit: We can also add a new line in here

2024-06-25 12:45 UTC, AndyTitu commented on Makefile
> +
nit: We can add a new line here for POSIX compliance

2024-06-25 13:18 UTC, MOmarMiraj commented on src/release/changelogs/0.1.0-beta.11-0010011
With the new changelog style, this makes much more sense. This has been updated.

2024-06-25 13:18 UTC, MOmarMiraj commented on src/release/scripts/prep-release.sh
> +sed -e "s/{{ build }}/$build/" -e "s/{{ version }}/$version/" "$version_template_file" > "$output_version_file"
Fixed.

2024-06-25 13:18 UTC, MOmarMiraj commented on src/release/templates/version.tpl.py
> +SDK_BUILD_NUMBER = "{{ build }}"
Added

2024-06-25 13:18 UTC, MOmarMiraj commented on src/release/version.py
> +SDK_BUILD_NUMBER = "0010011"
Added

2024-06-25 13:57 UTC, AndyTitu approved these changes
Functionally tested for all cases and it works fine. And code lgtm now.

2024-06-25 16:57 UTC, merged